### ISSUE TITLE
Tranquilpeak 1.3  roadmap

### ISSUE THREAD

**Issue by LouisBarranqueiro** [LouisBarranqueiro/tranquilpeak-hexo-theme#58]
Hi,  here is what's comming in Tranquilpeak 1.3 for the moment :  
- [x] : Internationalization. #48 
- [x] : Display inline fancybox images. #56 
- [x] : Add `image` tag to insert images, fancybox and create nice galleries
- [x] : Add `wide_image` tag to insert wide image in full width 
- [x] : Choose the size of cover image : partial (full width large height) or full size (full width and height)
- [x] : Choose alignment of meta information of a post (title, date and categories) : left, center or right
- [x] : Add cover caption feature to add caption to the cover image
- [x] : Add option to disable sidebar on all posts or temporarily on a post 
- [x] : Add caption feature for each photo of an image gallery

**If you have any ideas to improve the theme, write them in comment! :)**
